### ISSUE TITLE
Button demo fails

### ISSUE THREAD

**Issue by xoviat** [vecty-components/material#22]
The first issue that needs to be solved before running the project. Steps to reproduce:

1. Clone the project
2. `cd demos\button`
3. `GOOS=js GOARCH=wasm go build`
4. `mv button button.wasm`
5. `basic-http-server`

Note: `basic-http-server` is a basic, unsecure http server that's great for local development (not production). You can get it if you have rust installed with `cargo install basic-http-server`. If you don't want to install rust or basic-http-server, any http server will do. An http server is needed to get around browser XSS security.

Open the browser, developer tools, see the following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
wasm_exec.js:52 [signal 0xb code=0x0 addr=0x0 pc=0x0]
wasm_exec.js:52 
wasm_exec.js:52 goroutine 1 [running]:
wasm_exec.js:52 github.com/vecty-material/material/icon.(*I).iconDetails(0x45e000)
wasm_exec.js:52 	C:/Users/User/workspace/material/icon/icon.go:72 +0x4
wasm_exec.js:52 github.com/vecty-material/material/icon.(*I).Render(0x45e000)
wasm_exec.js:52 	C:/Users/User/workspace/material/icon/icon.go:31 +0x1a
wasm_exec.js:52 github.com/hexops/vecty.renderComponent({0xa17258, 0x45e000}, {0x0, 0x0})
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1040 +0x39
wasm_exec.js:52 github.com/hexops/vecty.render({0x3bd50, 0x45e000}, {0x0, 0x0})
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1001 +0xa
wasm_exec.js:52 github.com/hexops/vecty.(*HTML).reconcileChildren(0x45d5e0, 0x467c00)
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:422 +0x154
wasm_exec.js:52 github.com/hexops/vecty.(*HTML).reconcile(0x45d5e0, 0x0)
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:223 +0x49
wasm_exec.js:52 github.com/hexops/vecty.render({0x3bd00, 0x45d5e0}, {0x0, 0x0})
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:997 +0x6
wasm_exec.js:52 github.com/hexops/vecty.(*HTML).reconcileChildren(0x45ddc0, 0x468158)
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:422 +0x154
wasm_exec.js:52 github.com/hexops/vecty.KeyedList.reconcile({0x45ddc0, {0x0, 0x0}}, 0x45d880, {0x0, 0x0})
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:727 +0x33
wasm_exec.js:52 github.com/hexops/vecty.(*HTML).reconcileChildren(0x45d880, 0x468608)
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:419 +0x14c
wasm_exec.js:52 github.com/hexops/vecty.(*HTML).reconcile(0x45d880, 0x0)
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:223 +0x49
wasm_exec.js:52 github.com/hexops/vecty.render({0x3bd00, 0x45d880}, {0x0, 0x0})
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:997 +0x6
wasm_exec.js:52 github.com/hexops/vecty.(*HTML).reconcileChildren(0x45dce0, 0x468b60)
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:422 +0x154
wasm_exec.js:52 github.com/hexops/vecty.KeyedList.reconcile({0x45dce0, {0x0, 0x0}}, 0x45db20, {0x0, 0x0})
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:727 +0x33
wasm_exec.js:52 github.com/hexops/vecty.(*HTML).reconcileChildren(0x45db20, 0x469010)
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:419 +0x14c
wasm_exec.js:52 github.com/hexops/vecty.(*HTML).reconcile(0x45db20, 0x0)
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:223 +0x49
wasm_exec.js:52 github.com/hexops/vecty.render({0x3bd00, 0x45db20}, {0x0, 0x0})
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:997 +0x6
wasm_exec.js:52 github.com/hexops/vecty.(*HTML).reconcileChildren(0x45dc00, 0x469520)
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:422 +0x154
wasm_exec.js:52 github.com/hexops/vecty.(*HTML).reconcile(0x45dc00, 0x0)
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:223 +0x49
wasm_exec.js:52 github.com/hexops/vecty.renderComponent({0xa15958, 0x434050}, {0x0, 0x0})
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1063 +0x4b
wasm_exec.js:52 github.com/hexops/vecty.render({0xa15990, 0x434050}, {0x0, 0x0})
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1001 +0xa
wasm_exec.js:52 github.com/hexops/vecty.(*HTML).reconcileChildren(0x45d500, 0x469bb0)
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:422 +0x154
wasm_exec.js:52 github.com/hexops/vecty.(*HTML).reconcile(0x45d500, 0x0)
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:223 +0x49
wasm_exec.js:52 github.com/hexops/vecty.renderComponent({0x3c308, 0x444040}, {0x0, 0x0})
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1063 +0x4b
wasm_exec.js:52 github.com/hexops/vecty.renderIntoNode({0x2144c, 0xa}, {0x3ceb8, 0x40e0b0}, {0x3c308, 0x444040})
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1238 +0xa
wasm_exec.js:52 github.com/hexops/vecty.RenderBody({0x3c308, 0x444040})
wasm_exec.js:52 	C:/Users/User/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1190 +0x1a
wasm_exec.js:52 main.main()
wasm_exec.js:52 	C:/Users/User/workspace/material/demos/button/button_demo.go:22 +0x3
```

**Comment by VinceJnz** [comment]
The following is causing the crash because `c.MDC` is `nil`
```
func (c *I) iconDetails() (sizeClass string, isIconCode bool) {
	sizeClass = c.MDC.RootElement.Node().Get("SizePX").String()
...
```

`c.MDC` is set by `Apply` but `Apply` is not called before `iconDetails`
```
func (c *I) Apply(h *vecty.HTML) {
	sizeClass, isIconCode := c.iconDetails()
	switch {
	case c.MDC == nil:
		c.MDC = &base.MDC{}
	}
...
```

From what I understand `Apply` is called when `c` is rendered.
```
...
	return elem.Italic(
		vecty.Markup(
			c,
			vecty.MarkupIf(rootMarkup != nil, *rootMarkup),
		),
		vecty.If(!isIconCode, vecty.Text(c.Name)),
	)
...
```

And that's as far as I have got.

**Comment by VinceJnz** [comment]
Also there are other things that cause the button demo to crash.

I can get the demo to run if I comment out all the following:
...sections from `Render`
```
...
			&common.ToolbarHeader{
				Title:      "Buttons",
				Navigation: common.NavBack,
			},
...
```
```
...
					&formfield.FF{
						Label: "Disable buttons (excluding links)",
						Input: &checkbox.CB{
							Input: vecty.Markup(
								prop.ID("toggle-disabled"),
							),
							OnChange: func(thisCB *checkbox.CB, e *vecty.Event) {
								checked := e.Target.Get("checked").Bool()
								for _, b := range c.buttons {
									if b.Href != "" {
										continue
									}
									b.Disabled = checked
									vecty.Rerender(b)
								}
							},
						},
					},
...
```
... section from `renderBtnFieldSet`
```
...
					Icon: &icon.I{
						Name: "favorite",
					},
...
```

... line from `button` `Render`
```
...
	return elem.Button(
		vecty.Markup(
			c,
			//vecty.MarkupIf(rootMarkup != nil, *rootMarkup),
		),
		ico,
		base.RenderStoredChild(c.Label),
	)
...
```

**Comment by xoviat** [comment]
Note: this code is taken from the following two repositories:

https://github.com/agamigo/vecty-material
https://github.com/agamigo/vecty

The code in this repository should essentially be the same, but combined into one repository. However, the principle difference is that the old code uses the gopherjs API, which is now deprecated (replaced with syscall/js). 

You can see what the code was before:

https://github.com/agamigo/vecty-material/blob/master/icon/icon.go#L72

I think one mistake is `c.MDC.RootElement` should be replaced with `c.RootElement`. I'm not exactly clear how InternalObject worked, because it seems that it picked out `RootElement` which is magical.

**Comment by xoviat** [comment]
I'm going to run through the demos and comment out stuff until each one works. I'll then open issues for each problem. See how much you can fix; I'll be busy tomorrow but might work on some stuff on Sunday.

**Comment by VinceJnz** [comment]
In `iconDetails()` I tried `sizeClass = c.RootElement.Node().Get("SizePX").String()` but that didn't work either 

But I got it to run by doing the following.

Commented out the following line from `iconDetails()`
```
...
	//sizeClass = c.MDC.RootElement.Node().Get("SizePX").String()
...
```

Then I had to comment out the following line from `icon` `Render()`

```
...
	return elem.Italic(
		vecty.Markup(
			c,
			//vecty.MarkupIf(rootMarkup != nil, *rootMarkup),
		),
		vecty.If(!isIconCode, vecty.Text(c.Name)),
	)
...
```

**Comment by VinceJnz** [comment]
Leaving this line in
```
	//sizeClass = c.MDC.RootElement.Node().Get("SizePX").String()
```

Causes the following error
```
panic: runtime error: invalid memory address or nil pointer dereference wasm_exec.js:51:14
[signal 0xb code=0x0 addr=0x0 pc=0x0] wasm_exec.js:51:14
<empty string>
```

**Comment by xoviat** [comment]
if you have time, see if you can get the other demos working. Also, we need formfield working because that's a major component.

**Comment by xoviat** [comment]
Thanks for your help so far; much appreciated!

**Comment by VinceJnz** [comment]
what is the purpose of the code under `/material/material`?

**Comment by VinceJnz** [comment]
I have narrowed it down a bit. With these changes the button demo runs without commenting out any lines.

Here is what I have commented out to get it to run...

`button` `Render()`
```
...
	return elem.Button(
		vecty.Markup(
			c,
			//vecty.MarkupIf(rootMarkup != nil, *rootMarkup), //Comment this out and it runs
		),
		ico,
		base.RenderStoredChild(c.Label),
	)
...
```

`formField` `Render()`
```
...
	//inputID := applyer.FindID(c.Input) //Comment this out to get it to run
	return elem.Div(
		vecty.Markup(
			c,
		//vecty.MarkupIf(rootMarkup != nil, *rootMarkup), //Comment this out to get it to run
		),
		//c.Input,  //Comment this out to get it to run
		elem.Label(
			vecty.Markup(
			//vecty.MarkupIf(inputID != "", prop.For(inputID)), //Comment this out to get it to run
			),
			vecty.Text(c.Label),
		),
	)
...
```

`icon` `Render()`

```
...
	return elem.Italic(
		vecty.Markup(
			c,
			//vecty.MarkupIf(rootMarkup != nil, *rootMarkup), //Comment this out and it runs
		),
		vecty.If(!isIconCode, vecty.Text(c.Name)),
	)
...
```

`icon` `iconDetails()`
```
...
	//sizeClass = c.MDC.RootElement.Node().Get("SizePX").String() //Comment this out and it runs
	switch sizeClass {
...
```

**Comment by VinceJnz** [comment]
To get the checkbox_demo to run I had to do the following...

checkbox_demo.go
```
...
func (c *checkboxDemoView) Render() vecty.ComponentOrHTML {
...
			elem.Section(
				vecty.Markup(
					vecty.Class("hero"),
				),
				//c.checkboxes[HERO_ID], // Comment this out to make it run
				elem.Label(
					vecty.Markup(
						prop.ID("hero-checkbox-label"),
						prop.For(HERO_ID),
					),
					vecty.Text("Checkbox"),
				),
			),
...
```

index.html
```
...
  <body>
    <script src="https://material-components-web.appspot.com/assets/material-components-web.js" async=""></script>
    <script> //  src="https://rawcdn.githack.com/golang/go/04d8d249600bf7b350454175c521e0c251785956/misc/wasm/wasm_exec.js"></script>
    <script src="https://......./wasm_exec.js"></script>
    <script>
      (async () => {
        const resp = await fetch('checkbox.wasm');
        if (!resp.ok) {
          const pre = document.createElement('pre');
          pre.innerText = await resp.text();
          document.body.appendChild(pre);
          return;
        }
        const src = await resp.arrayBuffer();
        const go = new Go();
        const result = await WebAssembly.instantiate(src, go.importObject);
        go.run(result.instance);
      })();
    </script>
  </body>
...
```
