### ISSUE TITLE
demos\list issues

### ISSUE THREAD

**Issue by xoviat** [vecty-components/material#32]
not working

```
panic: runtime error: invalid memory address or nil pointer dereference
wasm_exec.js:51 [signal 0xb code=0x0 addr=0x0 pc=0x0]
wasm_exec.js:51 
wasm_exec.js:51 goroutine 1 [running]:
wasm_exec.js:51 github.com/vecty-material/material/ul.(*Item).Render(0x464000)
wasm_exec.js:51 	~/workspace/material/ul/list.go:153 +0x53
wasm_exec.js:51 github.com/hexops/vecty.renderComponent({0xa25ca0, 0x464000}, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1040 +0x39
wasm_exec.js:51 github.com/hexops/vecty.render({0x3f2c8, 0x464000}, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1001 +0xa
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcileChildren(0x44dce0, 0x462488)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:422 +0x154
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcile(0x44dce0, 0x0)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:223 +0x49
wasm_exec.js:51 github.com/hexops/vecty.renderComponent({0xa25c48, 0x44e600}, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1063 +0x4b
wasm_exec.js:51 github.com/hexops/vecty.render({0x3f2f0, 0x44e600}, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1001 +0xa
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcileChildren(0x44dc00, 0x462b60)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:422 +0x154
wasm_exec.js:51 github.com/hexops/vecty.KeyedList.reconcile({0x44dc00, {0x0, 0x0}}, 0x44db20, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:727 +0x33
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcileChildren(0x44db20, 0x463010)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:419 +0x14c
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcile(0x44db20, 0x0)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:223 +0x49
wasm_exec.js:51 github.com/hexops/vecty.renderComponent({0xa25930, 0x44e000}, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1063 +0x4b
wasm_exec.js:51 github.com/hexops/vecty.render({0xa25968, 0x44e000}, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1001 +0xa
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcileChildren(0x44c9a0, 0x4636a0)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:422 +0x154
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcile(0x44c9a0, 0x0)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:223 +0x49
wasm_exec.js:51 github.com/hexops/vecty.render({0x3f200, 0x44c9a0}, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:997 +0x6
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcileChildren(0x44ca80, 0x463bb0)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:422 +0x154
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).reconcile(0x44ca80, 0x0)
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:223 +0x49
wasm_exec.js:51 github.com/hexops/vecty.renderComponent({0x3f9e8, 0x424240}, {0x0, 0x0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1063 +0x4b
wasm_exec.js:51 github.com/hexops/vecty.renderIntoNode({0x2333b, 0xa}, {0x40798, 0x40e560}, {0x3f9e8, 0x424240})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1238 +0xa
wasm_exec.js:51 github.com/hexops/vecty.RenderBody({0x3f9e8, 0x424240})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1190 +0x1a
wasm_exec.js:51 main.main()
wasm_exec.js:51 	~/workspace/material/demos/list/list_demo.go:57 +0xc
```

**Comment by VinceJnz** [comment]
When I run up the demos using gaepher and navigate to the list demo I get "page not found".
There are no errors in the browser console.
When I build list.wasm directly there are no build errors.

**Comment by xoviat** [comment]
working
