### ISSUE TITLE
demos\menu issues

### ISSUE THREAD

**Issue by xoviat** [vecty-components/material#33]
not working

```
panic: syscall/js: call of Value.Invoke on undefined [recovered]
wasm_exec.js:51 	panic: syscall/js: call of Value.Invoke on undefined
wasm_exec.js:51 
wasm_exec.js:51 goroutine 1 [running]:
wasm_exec.js:51 github.com/vecty-material/material/gojs.CatchException(0x4b7c10)
wasm_exec.js:51 	~/workspace/material/gojs/errors.go:23 +0x3d
wasm_exec.js:51 panic({0x17520, 0x4e0c00})
wasm_exec.js:51 	C:/Program Files/Go/src/runtime/panic.go:1038 +0x29
wasm_exec.js:51 syscall/js.Value.New({{}, 0x0, 0x0}, {0x4b7a90, 0x1, 0x1})
wasm_exec.js:51 	C:/Program Files/Go/src/syscall/js/js.go:436 +0xa
wasm_exec.js:51 github.com/vecty-material/material/components/base.Start({0x5c340, 0x4389c0}, {{}, 0x7ff80001000000af, 0x411c98})
wasm_exec.js:51 	~/workspace/material/components/base/component.go:139 +0x68
wasm_exec.js:51 github.com/vecty-material/material/components/menu.(*M).Start(0x438980, {{}, 0x7ff80001000000af, 0x411c98})
wasm_exec.js:51 	~/workspace/material/components/menu/menu.go:64 +0x17
wasm_exec.js:51 github.com/vecty-material/material/base.(*MDC).Mount(0x40a798)
wasm_exec.js:51 	~/workspace/material/base/base.go:22 +0x17
wasm_exec.js:51 github.com/hexops/vecty.mount({0x4f6000, 0x32, 0x38})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1125 +0x19
wasm_exec.js:51 github.com/hexops/vecty.renderIntoNode({0x306c8, 0xa}, {0x5fed8, 0x40e6e0}, {0x5ed00, 0x4243c0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1264 +0x34
wasm_exec.js:51 github.com/hexops/vecty.RenderBody({0x5ed00, 0x4243c0})
wasm_exec.js:51 	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1190 +0x1a
wasm_exec.js:51 main.main()
wasm_exec.js:51 	~/workspace/material/demos/main.go:34 +0x7
wasm_exec.js:151 exit code: 2
```

**Comment by VinceJnz** [comment]
I thought I would take a look at this.
When I run up the demos using gaepher and navigate to the menu demo I get "page not found".
There are no errors in the browser console.
When I build menu.wasm directly there are no build errors.

**Comment by VinceJnz** [comment]
I've added `html.index` and `wasm_exec.js` to the menu folder and directly built `menu_demo.go` to `main.wasm` and am serving the menu folder.
 
I can get it to run if I comment out the following lines:

```
		elem.Main(
			elem.Div(vecty.Markup(vecty.Class("mdc-toolbar-fixed-adjust"))),
			elem.Section(
				vecty.Markup(vecty.Class("hero")),
				//heroM, // Comment this out to make it run
			),
			elem.Div(vecty.Markup(vecty.Class("demo-content")),
				elem.Div(vecty.Markup(prop.ID("demo-wrapper")),
					//demoM, // Comment this out to make it run
				),
``` 

However I can't get it to run under gaepher.

**Comment by xoviat** [comment]
'not found issues' fixed in #46, and list appears to be working as well now.

**Comment by xoviat** [comment]
see #49 

@VinceJnz Has the menu been working for you? I haven't been able to get it to work.

**Comment by VinceJnz** [comment]
@xoviat I'm not sure what the menu demo is supposed to do but it is crashing.

**Comment by VinceJnz** [comment]
Click button position `Top left` the click `Top right`

Browser console
```
panic: runtime error: invalid memory address or nil pointer dereference wasm_exec.js:51:14
[signal 0xb code=0x0 addr=0x0 pc=0x0] wasm_exec.js:51:14
<empty string> wasm_exec.js:51:14
goroutine 6 [running]: wasm_exec.js:51:14
github.com/vecty-material/material/demos/menu.(*MenuDemoView).Render.func3(0x464880, 0x4e8820) wasm_exec.js:51:14
	~/github/vecty-material/material/demos/menu/menu_demo.go:217 +0xa wasm_exec.js:51:14
github.com/vecty-material/material/radio.(*R).onChange(0x464880, 0x4e8820) wasm_exec.js:51:14
	~/github/vecty-material/material/radio/radio.go:81 +0xf wasm_exec.js:51:14
github.com/hexops/vecty.(*HTML).reconcileProperties.func1(0x6b118, 0x4f0990, 0x4f0970, 0x1, 0x1, 0x168c0, 0x48310) wasm_exec.js:51:14
	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:246 +0x13 wasm_exec.js:51:14
github.com/hexops/vecty.funcOf.func1(0x7ff80001000000d9, 0x4ece08, 0x4f0960, 0x1, 0x1, 0x4ece10, 0x25000) wasm_exec.js:51:14
	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom_js.go:60 +0x15 wasm_exec.js:51:14
syscall/js.handleEvent() wasm_exec.js:51:14
	/usr/local/go/src/syscall/js/func.go:96 +0x24 wasm_exec.js:51:14
exit code: 2 wasm_exec.js:151:14
```

**Comment by VinceJnz** [comment]
Click Default Menu Position `Top end` then click `Top start`

Browser console
```
panic: runtime error: invalid memory address or nil pointer dereference wasm_exec.js:51:14
[signal 0xb code=0x0 addr=0x0 pc=0x0] wasm_exec.js:51:14
<empty string> wasm_exec.js:51:14
goroutine 6 [running]: wasm_exec.js:51:14
github.com/vecty-material/material/components/menu.(*M).Component(0x0, 0x10970056) wasm_exec.js:51:14
	~/github/vecty-material/material/components/menu/menu.go:88 +0x2 wasm_exec.js:51:14
github.com/vecty-material/material/components/menu.(*M).SetAnchorCorner(0x0, 0x8) wasm_exec.js:51:14
	~/github/vecty-material/material/components/menu/menu.go:135 +0x2 wasm_exec.js:51:14
github.com/vecty-material/material/demos/menu.(*MenuDemoView).Render.func4(0x464c00, 0x4e8820) wasm_exec.js:51:14
	~/github/vecty-material/material/demos/menu/menu_demo.go:250 +0xf wasm_exec.js:51:14
github.com/vecty-material/material/radio.(*R).onChange(0x464c00, 0x4e8820) wasm_exec.js:51:14
	~/github/vecty-material/material/radio/radio.go:81 +0xf wasm_exec.js:51:14
github.com/hexops/vecty.(*HTML).reconcileProperties.func1(0x6b118, 0x4f0960, 0x4f0940, 0x1, 0x1, 0x168c0, 0x48310) wasm_exec.js:51:14
	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:246 +0x13 wasm_exec.js:51:14
github.com/hexops/vecty.funcOf.func1(0x7ff80001000001cd, 0x4ece20, 0x4f0930, 0x1, 0x1, 0x4ece28, 0x25000) wasm_exec.js:51:14
	~/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom_js.go:60 +0x15 wasm_exec.js:51:14
syscall/js.handleEvent() wasm_exec.js:51:14
	/usr/local/go/src/syscall/js/func.go:96 +0x24 wasm_exec.js:51:14
exit code: 2 wasm_exec.js:151:14
```

**Comment by VinceJnz** [comment]
There appears to be an error in `components/menu/menu.go`
https://github.com/vecty-material/material/blob/b7307bdd59792c17661060bb8ac9a0722123c6bc/components/menu/menu.go#L86

https://github.com/vecty-material/material/blob/b7307bdd59792c17661060bb8ac9a0722123c6bc/components/menu/menu.go#L134

The pointer var changes from `c` to `m`
`func (c *M)`
`func (m *M)`

However changing this doesn't fix the problem.

**Comment by xoviat** [comment]
That file is taken from here: https://github.com/agamigo/material/blob/master/menu/menu.go

I don't think the variable name makes a difference.

**Comment by VinceJnz** [comment]
https://github.com/vecty-material/material/blob/b7307bdd59792c17661060bb8ac9a0722123c6bc/demos/menu/menu_demo.go#L217

The problem with this is `demoM.MDC == <nil>`
I don't know where this is supposed to be initialized.

**Comment by VinceJnz** [comment]
https://github.com/vecty-material/material/blob/b7307bdd59792c17661060bb8ac9a0722123c6bc/components/menu/menu.go#L88

The problem is that `c == <nil>`
I don't know where this is supposed to be initialized.

**Comment by xoviat** [comment]
@bzub Can you answer some questions?

**Comment by VinceJnz** [comment]
So there are a couple of TODO's in menu.go that I think relate to the problems with the menu demo

https://github.com/vecty-material/material/blob/02eef6a07f6ce288c502ba8e0738e9d4e9c0e30e/menu/menu.go#L50

https://github.com/vecty-material/material/blob/02eef6a07f6ce288c502ba8e0738e9d4e9c0e30e/menu/menu.go#L113

**Comment by VinceJnz** [comment]
Also there was a folder /material/material which has now been renamed to material/components.
So does "Make initial values work in material package" now refer to components?

**Comment by VinceJnz** [comment]
Because of an earlier changes I had made to get the things working (see below) , `demoM` and `c` were not getting initialized. 
https://github.com/vecty-material/material/blob/02eef6a07f6ce288c502ba8e0738e9d4e9c0e30e/demos/menu/menu_demo.go#L343

https://github.com/vecty-material/material/blob/02eef6a07f6ce288c502ba8e0738e9d4e9c0e30e/demos/menu/menu_demo.go#L346

However when I remove the commented out lines menu crashes for other reasons.

**Comment by xoviat** [comment]
@bzub The main questions that I have are:

1. Where is the javascript `InternalObject` is stored in the structures and how is it bound to the [`vecty-material` component]( https://github.com/agamigo/vecty-material/blob/570bcb63eeafa1b30a1cabf13bfd4d22e304c471/menu/menu.go#L13) and/or the [`material`](https://github.com/agamigo/material/blob/master/menu/menu.go#L25) component. Was the menu demo working on gopherjs?
2. When/how is `Apply()` used? Why is it used over `Render()`?

**Comment by xoviat** [comment]
@VinceJnz the base folder in this repository corresponds to https://github.com/agamigo/vecty-material and the components folder corresponds to https://github.com/agamigo/material. The main difference is that this runs on wasm (and gopherjs, at least theoretically) and those run on (only) gopherjs.

**Comment by VinceJnz** [comment]
@xoviat What does this line do???
https://github.com/vecty-material/material/blob/f3c8b2118b910ca0fccef8ed3564abfb708d5e21/components/menu/after_start.go#L14-L15

I have been playing around with `js.Global()` to figure out what is happening here but I have no clue.
It crashes because `js.Global().Get("Object").Call("getOwnPropertyDescriptor", proto, "quickOpen")` returns undefined.

Here is the reference to this method:
<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor>

**Comment by VinceJnz** [comment]
I don't understand how this hangs together so not sure where to go next other than spending a lot time figuring out how it is supposed to work.

I don't know the answers to the questions that @bzub asked and I'm not sure where to look.

**Comment by xoviat** [comment]
The current code won't work as is because of an issue I just fixed.

**Comment by xoviat** [comment]
The purpose of that code is to preserve the current set/get while modifying the set/get. However, the new wasm standard requires a `js.Func`, which I [just fixed][1] in dialog.

[1]: https://github.com/vecty-material/material/commit/f3c8b2118b910ca0fccef8ed3564abfb708d5e21#diff-4d27646eca89be403d234c72d5fc7283e94dcb8a118a90d14f05db160805244aR13

**Comment by xoviat** [comment]
> It crashes because js.Global().Get("Object").Call("getOwnPropertyDescriptor", proto, "quickOpen") returns undefined.

Is `proto` a `js.Value`? That looks different than what we have in dialogue's `after_start`.

**Comment by xoviat** [comment]
@VinceJnz I resolved many of these issues in #56. I did not understand the full extent of the issues until now.

**Comment by VinceJnz** [comment]
Ah, okay. Thanks.
I'll update my clone.

**Comment by VinceJnz** [comment]
I'm interested to understand what the fixes are.

**Comment by VinceJnz** [comment]
So it still crashes

```
panic: syscall/js: call of Value.Invoke on undefined [recovered] wasm_exec.js:51:14
	panic: syscall/js: call of Value.Invoke on undefined wasm_exec.js:51:14
<empty string> wasm_exec.js:51:14
goroutine 1 [running]: wasm_exec.js:51:14
github.com/vecty-material/material/gojs.CatchException(0x4b7c18) wasm_exec.js:51:14
	/home/vince/github/vecty-material/material/gojs/errors.go:23 +0x41 wasm_exec.js:51:14
panic(0x1e5c0, 0x4e0c48) wasm_exec.js:51:14
	/usr/local/go/src/runtime/panic.go:965 +0x19 wasm_exec.js:51:14
syscall/js.Value.New(0x0, 0x0, 0x4b79f8, 0x1, 0x1, 0x0, 0x40ee00) wasm_exec.js:51:14
	/usr/local/go/src/syscall/js/js.go:436 +0xa wasm_exec.js:51:14
github.com/vecty-material/material/components/base.Start(0x6f708, 0x4389c0, 0x7ff80001000000af, 0x411c98, 0x0, 0x0) wasm_exec.js:51:14
	/home/vince/github/vecty-material/material/components/base/component.go:139 +0x5c wasm_exec.js:51:14
github.com/vecty-material/material/components/menu.(*M).Start(0x438980, 0x7ff80001000000af, 0x411c98, 0x1, 0x71aa8) wasm_exec.js:51:14
	/home/vince/github/vecty-material/material/components/menu/menu.go:64 +0x13 wasm_exec.js:51:14
github.com/vecty-material/material/base.(*MDC).Mount(0x40a798) wasm_exec.js:51:14
	/home/vince/github/vecty-material/material/base/base.go:22 +0x17 wasm_exec.js:51:14
github.com/hexops/vecty.mount(0x4f6000, 0x32, 0x38) wasm_exec.js:51:14
	/home/vince/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1125 +0xc wasm_exec.js:51:14
github.com/hexops/vecty.renderIntoNode(0x429d2, 0xa, 0x728f8, 0x40e7a0, 0x71b18, 0x4243c0, 0x728f8, 0x40e7a0) wasm_exec.js:51:14
	/home/vince/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1264 +0x27 wasm_exec.js:51:14
github.com/hexops/vecty.RenderBody(0x71b18, 0x4243c0) wasm_exec.js:51:14
	/home/vince/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:1190 +0xd wasm_exec.js:51:14
main.main() wasm_exec.js:51:14
	/home/vince/github/vecty-material/material/demos/main.go:34 +0x7 wasm_exec.js:51:14
exit code: 2
```

The following line returns `newMDCClassObj = <undefined>`
https://github.com/vecty-material/material/blob/ec048f1568dd6ba8fe28aeeddddb98c55eca1610/components/base/component.go#L135

Which causes the following line to crash
https://github.com/vecty-material/material/blob/ec048f1568dd6ba8fe28aeeddddb98c55eca1610/components/base/component.go#L139

`CCaseName == menu` and  `ClassName == MDCMenu`
* `MDCMenu` does not exist

The following does exist
* `MDCSimpleMenu`
* `MDCSimpleMenuFoundation`

**Comment by VinceJnz** [comment]
I found the following comment that suggests `MDCMenu` doesn't exist 
https://github.com/vecty-material/material/blob/ec048f1568dd6ba8fe28aeeddddb98c55eca1610/components/internal/mdctest/test_helpers.go#L37-L38

**Comment by VinceJnz** [comment]
I can't figure out where MDCMenu should be created.
I think something needs to create MDCMenu and add it to the mdc javascript object.

**Comment by xoviat** [comment]
@VinceJnz The reason that MDCMenu is not available is that this is locked to an old MDC version. I am upgrading to MDC 4, the latest version in #53, which will resolve these issues (though there are still issues, they can be resolved once MDC 4 is implemented). I have been trying to move as fast as I can so that you don't waste time, but it has taken me some time, and I've had to refactor significantly. 

I also want to write documentation so that the function of the code is clear, but I only have time for so much. To be clear, the presentation layer creates the HTML and then invokes the component layer to instantiate the MDC javascript object. 

The details to create the javascript object can be found using the developer tools console in Chrome and Edge:

![image](https://user-images.githubusercontent.com/49173759/135787273-a42751f0-7288-4cb7-bbfb-ae03eead6dd4.png)

Those map to the classname and the camelcasename (different because of the different MDC version): 

https://github.com/vecty-material/material/blob/8f5297b56ad7e771dc647a0d9f4f69e439355779/components/persistentdrawer/persistentdrawer.go#L42-L43

**Comment by VinceJnz** [comment]
Thanks.
I'm not in any hurry, it's just that I have time to poke around and learn, so long as I am helping and not hindering I'm happy to keep poking around.

**Comment by VinceJnz** [comment]
@xoviat The menu demo is currently crashing because the following List item does not have a key interface.
https://github.com/vecty-components/material/blob/56936a9bc0267f250c8425ee88a1148769aaaddf/demos/views/menu.go#L61

It can be fixed if the key function is removed from the list-item component
https://github.com/vecty-components/material/blob/56936a9bc0267f250c8425ee88a1148769aaaddf/ul/list.go#L111

Or by adding a key interface to the ItemDivider
https://github.com/vecty-components/material/blob/56936a9bc0267f250c8425ee88a1148769aaaddf/ul/list.go#L245

This would require adding a Key interface to the StaticComponent
https://github.com/vecty-components/material/blob/56936a9bc0267f250c8425ee88a1148769aaaddf/base/tools.go#L14

**Comment by xoviat** [comment]
Removing the key is not the right fix, because a key is needed to track the order of the elements. The second fix is not the right fix either, because staticcomponent does not need to always be keyed. The right fix is to extract the key from the html if present, using a new function similar to `ExtractMarkupFromLink`, and extract the key from  the markup, and set it in the staticcomponent if present. If I have time, I will implement that.

**Comment by VinceJnz** [comment]
So does that mean something needs to add a key to the html?

**Comment by VinceJnz** [comment]
I'm not sure I fully understand but are you saying that a `key` value has to be added to `StaticComponent` and then a function has to be created to read `key` from `ItemDivider` (`d`) and set the `key` value in `StaticComponent`?

```go
type StaticComponent struct {
	vecty.Core
	Child vecty.ComponentOrHTML
	key     string //Add key here????
}
```

```go
func ItemDivider() vecty.ComponentOrHTML {
	d := elem.ListItem(
		vecty.Markup(
			vecty.Class("mdc-list-divider"),
			vecty.Attribute("role", "separator"),
			vecty.Key(base.Key()) //Only if key == nil
		),
	)
	return base.RenderStoredChild(d)
}
```

**Comment by VinceJnz** [comment]
@xoviat It's failing the following check in vecty:
https://github.com/hexops/vecty/blob/5ca22e90668199cfb39978f65355d400d08e3f1d/dom.go#L392-L395

```
		keyer, isKeyer := nextChild.(Keyer)
		if hasKeyedChildren && !isKeyer {
			panic("vecty: all siblings must have keys when using keyed elements")
		}
```

I don't understand how a function similar to `ExtractMarkupFromLink` can fix this unless it returns a new type with a keyer interface.

**Comment by xoviat** [comment]
@VinceJnz see the post I wrote on the wiki: https://github.com/vecty-components/material/wiki

the idea is for staticcomponent to be keyed if the html is keyed. Then we can add a key to the html markup

**Comment by VinceJnz** [comment]
Which html markup would the key need to be added to?
Would it be added in `func ItemDivider()`?

Also: I read the post but I don't understand how this helps?

**Comment by soypat** [comment]
I've run the demo example using `wasmserve` and it works fine. Has  this issue been solved?

**Comment by VinceJnz** [comment]
There are still some problems.
For example the following is commented out because it causes a panic in vecty and I haven't been able to figure out how to resolve it. (This adds a divider line to the menu example)

https://github.com/vecty-components/material/blob/346312860111e5a96bb592ac99a404de24b88ece/demos/views/menu.go#L61

This is where vecty panics
```go
if nextChildRender != nil && prevChildRender != nil && nextChildRender == prevChildRender {
	panic("vecty: next child render must not equal previous child render (did the child Render illegally return a stored render variable?)")
}
```
https://github.com/hexops/vecty/blob/2abc3fbe89ef72f3767236869a48635516765135/dom.go#L510-L512

**Comment by VinceJnz** [comment]
There is a related issue logged against vecty

Panic when component uses ComonentOrHTML field as child #191
<https://github.com/hexops/vecty/issues/191>

And a good related discussion
Design: Determine how to manage component lifecycle #115:
 <https://github.com/hexops/vecty/issues/115>

**Comment by soypat** [comment]
I am not getting the same panic
```
panic: runtime error: invalid memory address or nil pointer dereference
wasm_exec.js:51 [signal 0xb code=0x0 addr=0x0 pc=0x0]
wasm_exec.js:51 
wasm_exec.js:51 goroutine 6 [running]:
wasm_exec.js:51 github.com/hexops/vecty.(*HTML).removeChild(0x6649a0, 0x64f5e0)
wasm_exec.js:51 	/home/pato/go/pkg/mod/github.com/hexops/vecty@v0.6.0/dom.go:655 +0x20
...
```
And even got a different panic when I tried it the first time. :shrug:

**Comment by VinceJnz** [comment]
I might have made some changes in my local copy ... let me check.

**Comment by VinceJnz** [comment]
I had been looking at this for a while and had made some changes to my local copy of vecty to try and understand the problem better. If I remove my local vecty changes I get the same error as you.

These are the changes I had made to `vecty/dom.go`:
```
func (h *HTML) removeChild(child *HTML) {
...
...
	//parentNode := child.node.Get("parentNode") //Added this because if the child has had the parentNode removed this will crash because the parentNode is nil
	//if parentNode == nil {
	//	return
	//}
	//parentNode.Call("removeChild", child.node)
	child.node.Get("parentNode").Call("removeChild", child.node)
}
```

**Comment by VinceJnz** [comment]
In my attempt to get the divider line to display I had also made some changes to the `materila/ul` `func ItemDivider()`
https://github.com/vecty-components/material/blob/346312860111e5a96bb592ac99a404de24b88ece/ul/list.go#L260-L268

Here are my changes:
```go
type D struct {
	vecty.Core
	key  string
	Root *vecty.HTML
}

func (d *D) Key() interface{} {
	return d.key
}

func NewD(h *vecty.HTML) vecty.ComponentOrHTML {
	D := &D{Root: h}
	D.key = base.Key()
	return D
}

func (d *D) Render() vecty.ComponentOrHTML {
	return d.Root
}

func ItemDivider() vecty.ComponentOrHTML { //bug caused from here?????
	d := elem.ListItem(
		vecty.Markup(
			vecty.Class("mdc-list-divider"),
			vecty.Attribute("role", "separator"),
			vecty.Key(base.Key()), //panic: vecty: all siblings must have keys when using keyed elements
		),
	)
	//return NewDividerComponent(d)
	ndc := NewD(d)
	return ndc
}
```

I don't fully understand what is happening but I was able to get the ItemDivider to display with some changes to vecty.
Which also included commenting out the following panic:
```go
// Determine the next child render.
nextChildRender, skip, mounters := render(nextChild, prevChild)
if nextChildRender != nil && prevChildRender != nil && nextChildRender == prevChildRender {
	panic("vecty: next child render must not equal previous child render (did the child Render illegally return a stored render variable?)")
}
```

https://github.com/hexops/vecty/blob/2abc3fbe89ef72f3767236869a48635516765135/dom.go#L508-L512

**Comment by soypat** [comment]
Your panic is happening because 

```go
func (d *D) Render() vecty.ComponentOrHTML {
	return d.Root
}
```
always returns the same backing component on every render! 

I believe this would fix the panic.

```go
type D struct {
	vecty.Core
	key  string
	Root func() *vecty.HTML
}

func (d *D) Key() interface{} {
	return d.key
}

func NewD(h func() *vecty.HTML) vecty.ComponentOrHTML {
	D := &D{Root: h}
	D.key = base.Key()
	return D
}

func (d *D) Render() vecty.ComponentOrHTML {
	return d.Root()
}

func ItemDivider() vecty.ComponentOrHTML { //bug caused from here?????
	d := func() *vecty.HTML {
		return elem.ListItem(
			vecty.Markup(
				vecty.Class("mdc-list-divider"),
				vecty.Attribute("role", "separator"),
				vecty.Key(base.Key()), //panic: vecty: all siblings must have keys when using keyed elements
			),
		)
	}
	ndc := NewD(d)
	return ndc
}
```

**Comment by soypat** [comment]
![image](https://user-images.githubusercontent.com/26156425/149146240-eabd65a9-4dc6-4d1f-b372-96de0c90966e.png)

Sure enough it works on my machine with no issues :smile: 

I'd love to contribute more to this project but I am kind of in the dark with what is broken, what needs to be upgraded and whatnot. The issues I've looked at are quite brief in detail.

**Comment by VinceJnz** [comment]
Thanks, I'm relatively new to development.

@xoviat is the best person to provide the background.

**Comment by VinceJnz** [comment]
@soypat I have applied your suggested changes to the branch I was using and it all appears to work correctly.

https://github.com/vecty-components/material/blob/028063194c84372b6695428f42e37de7975f5caf/ul/list.go#L227-L240
